name: set-invironment
author: "Jaeyun"
description: "Use set-environment module in github action"
inputs:
  REF_TYPE:
    description: "branch or tag"
    required: true
    default: "branch"
  BASE_REF:
    description: "dev or master"
    required: true
    default: "dev"
outputs:
  environment:
    description: "set env"
    value: ${{ steps.set-environment.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: Set env
      id: set-env
      shell: bash
      run: |
        if [[ ${{ inputs.REF_TYPE }} == "tag" ]]; then
          echo "environment=qa" >> $GITHUB_OUTPUT
          exit 0  
        fi

        if [[ ${{ inputs.REF_TYPE }} == "branch" ]]; then
          echo "environment=dev" >> $GITHUB_OUTPUT
          if [[ ${{ inputs.BASE_REF }} == "master" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
        fi
    - name: Check env
      shell: bash
      run: echo ${{ steps.set-env.outputs.environment }}
